/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private App app;

    @BeforeEach
    void setUp() {
        app = new App();
    }

    @Test
    void appHasAGreeting() {
        assertNotNull(app.getGreeting(), "app should have a greeting");
    }

    @Test
    void testMainMethodDoesNotThrowException() {
        assertDoesNotThrow(() -> App.main(new String[]{}));
    }
}
