/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    private static Scanner scanner = new Scanner(System.in);
    private static PackingSimulator simulator = new PackingSimulator();

    public static void main(String[] args) {
        boolean running = true;
        while (running) {
            displayMenu();
            int choice = getValidChoice();
            
            switch (choice) {
                case 1:
                    runNewSimulation();
                    break;
                case 2:
                    displayDetailedStatistics();
                    break;
                case 3:
                    running = false;
                    break;
                default:
                    System.out.println("Invalid option. Please try again.");
            }
        }
        scanner.close();
        System.out.println("Thank you for using the Package Simulator!");
    }

    private static void displayMenu() {
        System.out.println("\n=== Package Simulator Menu ===");
        System.out.println("1. Run new simulation");
        System.out.println("2. Display detailed statistics");
        System.out.println("3. Exit");
        System.out.print("Enter your choice (1-3): ");
    }

    private static int getValidChoice() {
        while (!scanner.hasNextInt()) {
            System.out.println("Please enter a valid number.");
            scanner.next();
        }
        return scanner.nextInt();
    }

    private static void runNewSimulation() {
        System.out.print("Enter number of packages to simulate: ");
        while (!scanner.hasNextInt()) {
            System.out.println("Please enter a valid number.");
            scanner.next();
        }
        int packageCount = scanner.nextInt();
        
        if (packageCount > 0) {
            simulator = new PackingSimulator(); // Reset simulator
            simulator.generatePackages(packageCount);
            simulator.runSimulation();
            simulator.printStatistics();
        } else {
            System.out.println("Number of packages must be greater than 0");
        }
    }

    private static void displayDetailedStatistics() {
        if (simulator.getContainers().isEmpty()) {
            System.out.println("No simulation has been run yet.");
            return;
        }
        
        System.out.println("\n=== Detailed Statistics ===");
        System.out.println("Container Details:");
        for (Container container : simulator.getContainers()) {
            System.out.printf("Container %s: %.2f%% utilized, %d packages\n",
                container.getId(),
                container.getUtilization(),
                container.getPackages().size());
        }
        
        System.out.println("\nUnpacked Packages:");
        for (Package pkg : simulator.getPendingPackages()) {
            System.out.println(pkg.toString());
        }
    }
}
